# Generated by Django 4.2.7 on 2025-07-18 12:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1)),
                ('documento', models.CharField(max_length=18, unique=True)),
                ('rg_ie', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('desconto_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], default='ativo', max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
